# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build Image
        run: mvn spring-boot:build-image
        env:
          MAVEN_USERNAME: jiangtj
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          docker login -u jiangtj -p ${{ secrets.MYPASS }}
          docker push jiangtj/sba-server:latest

